[project]
name = "repl-nix-log-in-with-hacker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "pandas>=2.2.3",
    "setuptools>=75.6.0",
]
